"""Dependency-free preview server for the AI WhiteSec dashboard.

This is only a local UI/API preview. The Docker/FastAPI/PostgreSQL stack remains
the implementation used for integration and deployment.
"""

from __future__ import annotations

from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import argparse
import json
import mimetypes
from pathlib import Path
from urllib.parse import urlparse
import uuid


PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATIC_ROOT = PROJECT_ROOT / "backend" / "app" / "static"
RUNS: list[dict] = []


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def sample_finding(run_id: str, source: str, status: str, cwe: str, path: str, function: str, line: int, title: str, severity: str, confidence: float | None = None) -> dict:
    return {
        "id": str(uuid.uuid4()),
        "run_id": run_id,
        "source": source,
        "file_path": path,
        "function_name": function,
        "start_line": line,
        "end_line": line + 3,
        "cwe": cwe,
        "severity": severity,
        "confidence": confidence,
        "title": title,
        "description": "Demonstration evidence generated by the dependency-free preview server.",
        "evidence": {"preview": True},
        "fingerprint": uuid.uuid4().hex,
        "combination_status": status,
        "remediation": "Review the evidence and apply the framework's secure coding guidance.",
        "created_at": now_iso(),
    }


def seed_run() -> dict:
    run_id = str(uuid.uuid4())
    run = {
        "id": run_id,
        "project": "AI WhiteSec Demo",
        "repository": "demo/vulnerable-python-app",
        "commit_sha": uuid.uuid4().hex[:12],
        "branch": "main",
        "trigger": "preview",
        "status": "completed",
        "model_version": "mock-codebert-5cwe-v1",
        "checkmarx_config": "demo-sast",
        "started_at": now_iso(),
        "completed_at": now_iso(),
        "duration_seconds": 37.4,
        "findings": [
            sample_finding(run_id, "combined", "AGREEMENT", "CWE-89", "app/users.py", "find_user", 41, "Agreement: SQL injection", "high", 0.93),
            sample_finding(run_id, "combined", "SAST_ONLY", "CWE-22", "app/files.py", "download", 19, "SAST only: path traversal", "medium"),
            sample_finding(run_id, "combined", "AI_ONLY", "CWE-79", "app/templates.py", "preview", 8, "AI only: cross-site scripting", "medium", 0.81),
        ],
    }
    RUNS.insert(0, run)
    return run


def summary() -> dict:
    combined = [finding for run in RUNS for finding in run["findings"] if finding["source"] == "combined"]
    statuses: dict[str, int] = {}
    cwes: dict[str, int] = {}
    for finding in combined:
        statuses[finding["combination_status"]] = statuses.get(finding["combination_status"], 0) + 1
        cwes[finding["cwe"]] = cwes.get(finding["cwe"], 0) + 1
    return {
        "runs": {"total": len(RUNS), "completed": sum(run["status"] == "completed" for run in RUNS)},
        "combined_findings": len(combined),
        "by_combination_status": statuses,
        "by_cwe": cwes,
    }


class Handler(BaseHTTPRequestHandler):
    server_version = "AIWhiteSecPreview/0.1"

    def send_json(self, payload: object, status: int = 200) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def serve_file(self, path: Path) -> None:
        try:
            resolved = path.resolve(strict=True)
            resolved.relative_to(STATIC_ROOT.resolve())
        except (FileNotFoundError, ValueError):
            self.send_error(404)
            return
        body = resolved.read_bytes()
        content_type = mimetypes.guess_type(resolved.name)[0] or "application/octet-stream"
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802
        path = urlparse(self.path).path
        if path == "/":
            self.serve_file(STATIC_ROOT / "index.html")
        elif path.startswith("/static/"):
            self.serve_file(STATIC_ROOT / path.removeprefix("/static/"))
        elif path == "/health":
            self.send_json({"status": "ok", "service": "preview", "version": "0.1.0"})
        elif path == "/api/v1/dashboard/summary":
            self.send_json(summary())
        elif path == "/api/v1/runs":
            self.send_json([{key: value for key, value in run.items() if key != "findings"} for run in RUNS])
        elif path.startswith("/api/v1/runs/"):
            run_id = path.rsplit("/", 1)[-1]
            run = next((item for item in RUNS if item["id"] == run_id), None)
            self.send_json(run if run else {"detail": "Scan run not found"}, 200 if run else 404)
        else:
            self.send_error(404)

    def do_POST(self) -> None:  # noqa: N802
        path = urlparse(self.path).path
        content_length = int(self.headers.get("Content-Length", "0"))
        if content_length:
            self.rfile.read(content_length)
        if path == "/api/v1/demo/seed":
            self.send_json(seed_run(), 201)
        else:
            self.send_json({"detail": "Preview endpoint not implemented"}, 404)

    def log_message(self, format: str, *args: object) -> None:
        print(f"[{self.log_date_time_string()}] {format % args}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the dependency-free dashboard preview")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--seed", action="store_true", help="Create one demo scan at startup")
    args = parser.parse_args()
    if args.seed:
        seed_run()
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"AI WhiteSec preview running at http://{args.host}:{args.port}", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()

